local assert = require('luassert')
local helpers = require('test.helpers')

describe('lean', function()
  it('setup', function()
    require('lspconfig').leanls.setup({})
  end)

  describe('existing', function()
  describe('file', function()
    it('startup', function()
      vim.api.nvim_command("edit fixtures/example-project-1/Test.lean")
      vim.api.nvim_command("set ft=lean")
      helpers.wait_for_ready_lsp()
      assert.equal(1, #vim.lsp.get_active_clients())
    end)

    it('hover', function()
      local text = helpers.try_lsp_req({3, 20}, "textDocument/hover", helpers.hover_parser)
      assert.message("hover request never received parseable data").is_truthy(text)
      assert.has_all(text, {"test : Nat"})
    end)

    it('definition', function()
      local text = helpers.try_lsp_req({3, 20}, "textDocument/definition", helpers.definition_parser)
      assert.message("definition request never received parseable data").is_truthy(text)
      -- case-insensitive because MacOS FS is case-insensitive
      assert.has_all(text:lower(), {("fixtures/example-project-1/Test/Test1.lean"):lower()})
    end)
  end)

  describe('nested file', function()
    it('startup', function()
      vim.api.nvim_command("edit fixtures/example-project-1/Test/Test1.lean")
      vim.api.nvim_command("set ft=lean")
      helpers.wait_for_ready_lsp()
      assert.equal(1, #vim.lsp.get_active_clients())
    end)

    it('hover', function()
      local text = helpers.try_lsp_req({1, 19}, "textDocument/hover", helpers.hover_parser)
      assert.message("hover request never received parseable data").is_truthy(text)
      assert.has_all(text, {"5 : Nat"})
    end)
  end)
  end)

  -- tests neovim/nvim-lspconfig#1041
  describe('new', function()
  describe('file', function()
    it('startup', function()
      vim.api.nvim_command("edit fixtures/example-project-1/Foo.lean")
      vim.api.nvim_command("set ft=lean")
      helpers.wait_for_ready_lsp()
      vim.api.nvim_command("0read fixtures/example-project-1/Test.lean")
      assert.equal(1, #vim.lsp.get_active_clients())
    end)

    it('hover', function()
      local text = helpers.try_lsp_req({3, 20}, "textDocument/hover", helpers.hover_parser)
      assert.message("hover request never received parseable data").is_truthy(text)
      assert.has_all(text, {"test : Nat"})
    end)

    it('definition', function()
      local text = helpers.try_lsp_req({3, 20}, "textDocument/definition", helpers.definition_parser)
      assert.message("definition request never received parseable data").is_truthy(text)
      assert.has_all(text:lower(), {("fixtures/example-project-1/Test/Test1.lean"):lower()})
    end)
  end)
  describe('nested file', function()
    it('startup', function()
      vim.api.nvim_command("edit! fixtures/example-project-1/Test/Foo1.lean")
      vim.api.nvim_command("set ft=lean")
      helpers.wait_for_ready_lsp()
      vim.api.nvim_command("0read fixtures/example-project-1/Test/Test1.lean")
      assert.equal(1, #vim.lsp.get_active_clients())
    end)

    it('hover', function()
      local text = helpers.try_lsp_req({1, 19}, "textDocument/hover", helpers.hover_parser)
      assert.message("hover request never received parseable data").is_truthy(text)
      assert.has_all(text, {"5 : Nat"})
    end)
  end)
  end)

  describe('second project', function()
    it('startup', function()
      vim.api.nvim_command("edit! fixtures/example-project-2/Test.lean")
      vim.api.nvim_command("set ft=lean")
      helpers.wait_for_ready_lsp()
      assert.equal(2, #vim.lsp.get_active_clients())
    end)

    it('hover', function()
      local text = helpers.try_lsp_req({3, 21}, "textDocument/hover", helpers.hover_parser)
      assert.message("hover request never received parseable data").is_truthy(text)
      assert.has_all(text, {"test : Prop"})
    end)

    it('definition', function()
      local text = helpers.try_lsp_req({3, 21}, "textDocument/definition", helpers.definition_parser)
      assert.message("definition request never received parseable data").is_truthy(text)
      assert.has_all(text:lower(), {("fixtures/example-project-2/Test/Test1.lean"):lower()})
    end)
  end)

  -- It seems this isn't supported by Lean 4 at the moment?
  describe('standalone file', function()
    pending('startup', function()
      vim.api.nvim_command("edit /tmp/Foo.lean")
      vim.api.nvim_command("set ft=lean")
      helpers.wait_for_ready_lsp()
      vim.api.nvim_command("0read fixtures/example-project-1/Test/Test1.lean")
      assert.equal(3, #vim.lsp.get_active_clients())
    end)

    pending('hover', function()
      local text = helpers.try_lsp_req({1, 19}, "textDocument/hover", helpers.hover_parser)
      assert.message("hover request never received parseable data").is_truthy(text)
      assert.has_all(text, {"5 : Nat"})
    end)
  end)
end)
