name: default

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '25 0 * * *'

permissions:
  issues: write

jobs:
  leanls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: date +%F > todays-date
      # ideally we'd use anchors here to avoid duplicating this code, but this isn't implemented yet;
      # see actions/runner#1182
      - name: Restore cache for today's nightly.
        uses: actions/cache@v2
        with:
          path: _neovim
          key: ${{ runner.os }}-x64-${{ hashFiles('todays-date') }}
      - name: Install nvim
        run: |
          curl -OL https://raw.githubusercontent.com/norcalli/bot-ci/master/scripts/github-actions-setup.sh
          source github-actions-setup.sh nightly-x64
          echo $(realpath ./_neovim/bin) >> $GITHUB_PATH
      - name: Run setup
        run: TEST=leanls make setup
      - name: Run tests
        run: TEST=leanls make test
        continue-on-error : true
      - name: Update issues
        run: ./update_issues.sh leanls '${{ secrets.GITHUB_TOKEN }}' '${{ github.repository }}' '${{ github.run_id }}' '${{ github.sha }}' '${{ github.event_name }}'
  lean3ls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: date +%F > todays-date
      # ideally we'd use anchors here to avoid duplicating this code, but this isn't implemented yet;
      # see actions/runner#1182
      - name: Restore cache for today's nightly.
        uses: actions/cache@v2
        with:
          path: _neovim
          key: ${{ runner.os }}-x64-${{ hashFiles('todays-date') }}
      - name: Install nvim
        run: |
          curl -OL https://raw.githubusercontent.com/norcalli/bot-ci/master/scripts/github-actions-setup.sh
          source github-actions-setup.sh nightly-x64
          echo $(realpath ./_neovim/bin) >> $GITHUB_PATH
      - name: Run setup
        run: TEST=lean3ls make setup
      - name: Run tests
        run: TEST=lean3ls make test
        continue-on-error : true
      - name: Update issues
        run: ./update_issues.sh lean3ls '${{ secrets.GITHUB_TOKEN }}' '${{ github.repository }}' '${{ github.run_id }}' '${{ github.sha }}' '${{ github.event_name }}'
