name: default

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '25 0 * * *'

permissions:
  issues: write

jobs:
  default:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        config: [leanls, lean3ls]
        include:
          - os: ubuntu-latest
            os-name: linux
    steps:
      - uses: actions/checkout@v2
      - run: date +%F > todays-date
      - name: Restore cache for today's nightly.
        uses: actions/cache@v2
        with:
          path: _neovim
          key: ${{ runner.os }}-x64-${{ hashFiles('todays-date') }}
      - name: Install nvim
        run: |
          curl -OL https://raw.githubusercontent.com/norcalli/bot-ci/master/scripts/github-actions-setup.sh
          source github-actions-setup.sh nightly-x64
          echo $(realpath ./_neovim/bin) >> $GITHUB_PATH
          echo ID 1 ${{ job.container.id }}
          echo ID 2 ${{ job.container.network }}
          echo ID 3 $GITHUB_RUN_ID
          echo ID 4 $GITHUB_RUN_NUMBER
          echo ID 5 $GITHUB_ACTION
          echo ID 6 $GITHUB_ACTION_PATH
          echo ID 7 $GITHUB_JOB
          echo ID 8 $GITHUB_WORKFLOW
      - name: Run setup
        run: TEST=${{ matrix.config }} make setup
      - name: Run tests
        run: TEST=${{ matrix.config }} make test
        continue-on-error : true
      - name: Update issues
        run: ./update_issues.sh '${{ matrix.config }}' '${{ secrets.GITHUB_TOKEN }}' '${{ github.repository }}' '${{ github.run_id }}' '${{ github.sha }}' '${{ github.event_name }}'
