name: default

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '25 8 * * *'

permissions:
  issues: write

jobs:
  default:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        config: [leanls, lean3ls]
    steps:
      - uses: actions/checkout@v2
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.6.0
      - name: Run setup
        run: TEST=${{ matrix.config }} make setup
      - name: Run tests
        run: TEST=${{ matrix.config }} make test
        continue-on-error : true
      - name: Update issues
        run: ./update_issues.sh '${{ matrix.config }}' '${{ matrix.os }}' '${{ secrets.GITHUB_TOKEN }}'
