name: default

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '25 8 * * *'

permissions:
  issues: write

jobs:
  default:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        config: [leanls, lean3ls]
    steps:
      - uses: actions/checkout@v2
      - run: date +%F > todays-date
      - name: Restore cache for today's nightly.
        uses: actions/cache@v2
        with:
          path: _neovim
          key: ${{ runner.os }}-x64-${{ hashFiles('todays-date') }}
        if: runner.os == 'Linux'
      - name: Install nvim
        run: |
          curl -OL https://raw.githubusercontent.com/norcalli/bot-ci/master/scripts/github-actions-setup.sh
          source github-actions-setup.sh nightly-x64
          echo $(realpath ./_neovim/bin) >> $GITHUB_PATH
        if: runner.os == 'Linux'
      - name: Install nvim
        run: |
          brew update
          brew install --head neovim
        if: runner.os == 'macOS'
      - name: Run setup
        run: TEST=${{ matrix.config }} make setup
      - name: Run tests
        run: TEST=${{ matrix.config }} make test
        continue-on-error : true
      - name: Update issues
        run: ./update_issues.sh '${{ matrix.config }}' '${{ matrix.os }}' '${{ secrets.GITHUB_TOKEN }}'
