name: default

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '25 8 * * *'

permissions:
  issues: write

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        server:
          - angularls
          - ansiblels
          - arduino_language_server
          - bashls
          - bicep
          - clangd
          - clojure_lsp
          - cmake
          - codeqlls
          - csharp_ls
          - cssls
          - dartls
          - denols
          - diagnosticls
          - dockerls
          - dotls
          - efm
          - elixirls
          - elmls
          - ember
          - emmet_ls
          - erlangls
          - esbonio
          - eslint
          - fortls
          - fsautocomplete
          - gopls
          - graphql
          - groovyls
          - hls
          - html
          - intelephense
          - jdtls
          - jedi_language_server
          - jsonls
          - jsonnet_ls
          - kotlin_language_server
          - lemminx
          - ltex
          - ocamlls
          - omnisharp
          - phpactor
          - powershell_es
          - prismals
          - puppet
          - purescriptls
          - pylsp
          - pyright
          - quick_lint_js
          - rescriptls
          - rome
          - rust_analyzer
          - serve_d
          - solang
          - solargraph
          - sorbet
          - spectral
          - sqlls
          - sqls
          - stylelint_lsp
          - sumneko_lua
          - svelte
          - tailwindcss
          - terraformls
          - texlab
          - tflint
          - tsserver
          - vala_ls
          - vimls
          - volar
          - vuels
          - yamlls
          - zls
    steps:
      - uses: actions/checkout@v2
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.6.0
      - name: Run tests
        run: docker run --rm -e TEST=$TEST -v $PWD:/lspconfig-tests williamboman/nvim-lspconfig-test:ubuntu bash -c 'cd /lspconfig-tests && make setup && make test'
        env:
          TEST: ${{ matrix.config }}
      # - name: Update issues
      #   run: ./update_issues.sh '${{ matrix.config }}' '${{ matrix.os }}' '${{ secrets.GITHUB_TOKEN }}'
